### ISSUE TITLE
pypi release

### ISSUE THREAD

**Issue by brean** [locusrobotics/aiorospy#23]
Hi!

How about a pypi release for this so I can install aiorospy using pip?

Andreas

**Comment by brean** [comment]
Hey,

I hope you are not mad at me but I just created an own release on pypi myself because this makes my life easier:
https://pypi.org/project/aiorospy/

I am happy to add you as maintainer or hand it over to you guys/locusrobotics completely!

Cheers,

Andreas

**Comment by ablakey** [comment]
Sorry for not responding to your original message.

It's curious that it's so important that this gets into Pypi given that it is a fairly traditional ROS package, depending on numerous packages not found in Pypi. We can't take it over as maintainer as it won't exactly work right when others try to pip install it. 

The better approach is to get this building for Melodic (https://github.com/locusrobotics/aiorospy/issues/15) so that it can be apt installed and pull in its dependencies.

Regarding the pypi repo you created. If this helps you in some way, great. But please base it on a fork of your own and explicitly report in the pypi description that this is from a fork (and link to the fork).
